kumuluzee:
  name: posts
  env:
    name: dev
  version: 1.0.0
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
      etcd:
        hosts: http://192.168.99.100:2379
      ttl: 30
      ping-interval: 5

  server:
    base-url: http://192.168.99.100:8091
    http:
      port: 8091

  health:
      servlet:
        mapping: /health
        enabled: true
      checks:
        disk-space-health-check:
          threshold: 1000000000
  metrics:
          web-instrumentation:
            - name: metricsEndpoint
              url-pattern: /metrics/*
            - name: customersEndpoint
              url-pattern: /v1/posts/*

