apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: posts-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - image: cleptes/posts:0.02
        name: posts
        imagePullPolicy: Always
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://169.51.16.117:32716
          - name: KUMULUZEE_VERSION
            value: 1.0.1
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-posts:5441/posts
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: userdb
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: postgres

        ports:
        - containerPort: 8091
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8091
          initialDelaySeconds: 20
          periodSeconds: 3

